version: '3.8'

services:
  user-service:
    volumes:
      - ./services/user-service:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  product-service:
    volumes:
      - ./services/product-service:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development 